llm:
  provider: ollama
  base_url: "http://127.0.0.1:11434"
  model: "llama3.1:8b"
  timeout_s: 120
  temperature: 0.2

email: 
  default_provider : gmail
  providers:
    gmail:
      type: gmail_oauth
      credentials_path: "secrets/gmail_credentials.json"
      token_path: "secrets/gmail_token.json"

profile: 
  display_name : "Jason"
  email_siganture: "Best regards, \n Jason"
  default_email_language: "en"
  important_senders: ["@gradescope.com","arafferty@carleton.edu"]
  important_keywords: ["cs department", "research", "application", "scholarship", "grade"]

